# NOTICE - DO NOT EDIT this file in this folder. Copy this to a local .DEV folder and edit there.

# Before running these commands, you must have the USBIPD-WIN project installed on Windows.
# Follow the instructions at https://learn.microsoft.com/en-us/windows/wsl/connect-usb

# This script allows you to attach usb devices on Windows to WSL. 
# First the USB device must be shared, then it can be attached. See `share-usb.ps1`. 

# Unfortunately if WSL is using the USB device, it cannot be used on Windows, and vice versa. 
# Script `attach-usb.ps1` should be run whenever you want to use the device in WSL

# To attach the USB device, run the following command. 
# Ensure that a WSL command prompt is open in order to keep the WSL 2 lightweight VM active. 
# Note that as long as the USB device is attached to WSL, it cannot be used by Windows. 
# Once attached to WSL, the USB device can be used by any distribution running as WSL 2. 
# Verify that the device is attached using usbipd list. 
# From the WSL prompt, run `lsusb` to verify that the USB device is listed and can be interacted with using Linux tools.



# -- EDIT BELOW -- #


# UNCOMMENT THE NEXT TWO LINES AND EDIT THE BUS ID WITH THE CORRECT ONE FOR YOUR USB DEVICE (use `usbipd list` to check your BUSID)
#usbipd attach --wsl --busid <busid> 
#Write-Host "Don't forget to check to see that this device is available in WSL. Run `lsusb` in WSL to verify" -ForegroundColor Green 

# COMMENT THE NEXT LINE
Write-Host "NO USB DEVICE SET FOR ATTACHING. EDIT THIS SCRIPT AND UPDATE THE LINE ABOVE THIS ONE." -ForegroundColor Red 
