# NOTICE - DO NOT EDIT this file in this folder. Copy this to a local .DEV folder and edit there.

# Before running these commands, you must have the USBIPD-WIN project installed on Windows.
# Follow the instructions at https://learn.microsoft.com/en-us/windows/wsl/connect-usb

Write-Host "Retrieving shared USB devices..." -ForegroundColor Cyan
$usbDevices = usbipd list

if (-not $usbDevices) {
    Write-Host "No USB devices found. Ensure your USBIPD service is running and devices are connected." -ForegroundColor Red
    exit
}

# Parse the `usbipd list` output using regex
$deviceList = @()
$usbDevices -split "`n" | ForEach-Object {
    if ($_ -match "^(?<BUSID>\S+)\s+(?<VIDPID>\S+)\s+(?<Device>.+?)\s+(?<State>Shared|Not shared|Attached)$") {
        $deviceList += [PSCustomObject]@{
            BUSID   = $matches['BUSID']
            VIDPID  = $matches['VIDPID']
            Device  = $matches['Device']
            State   = $matches['State']
        }
    }
}

if (-not $deviceList) {
    Write-Host "No USB devices were found. Ensure devices are connected and try again." -ForegroundColor Red
    exit
}

# Filter shared and attached devices
$sharedDevices = $deviceList | Where-Object { $_.State -eq "Shared" }
$attachedDevices = $deviceList | Where-Object { $_.State -eq "Attached" }

# Check if there are no shared devices
if (-not $sharedDevices) {
    Write-Host "No devices are in the Shared state. Ensure the USB device is shared using 'usbipd share --busid <BUSID>'." -ForegroundColor Yellow
    if ($attachedDevices) {
        Write-Host "The following devices are already attached:" -ForegroundColor Cyan
        $attachedDevices | ForEach-Object {
            Write-Host ("BUSID: {0} | VID:PID: {1} | Device: {2}" -f $_.BUSID, $_.VIDPID, $_.Device) -ForegroundColor Yellow
        }
    }
    exit
}

# Display the list of shared devices for selection
Write-Host "Select a device from the list in the graphical window to attach..."
$selectedDevice = $sharedDevices | Out-GridView -Title "Select a USB Device to Attach to WSL" -PassThru

if (-not $selectedDevice) {
    Write-Host "No device selected. Exiting." -ForegroundColor Yellow
    exit
}

# Attach the selected BUSID
$selectedBusID = $selectedDevice.BUSID
usbipd attach --wsl --busid $selectedBusID
if ($LASTEXITCODE -eq 0) {
    Write-Host "Device with BUSID $selectedBusID successfully attached to WSL." -ForegroundColor Green
    Write-Host "Run 'lsusb' in WSL to verify the device is available." -ForegroundColor Green
} else {
    Write-Host "Failed to attach device with BUSID $selectedBusID. Check the device state and try again." -ForegroundColor Red
}
