# NOTICE - DO NOT EDIT this file in this folder. Copy this to a local .DEV folder and edit there.

# Before running these commands, you must have the USBIPD-WIN project installed on Windows.
# Follow the instructions at https://learn.microsoft.com/en-us/windows/wsl/connect-usb

# This script allows you to detach usb devices from WSL back to Windows without physically unplugging the USB device

Write-Host "Retrieving attached USB devices..." -ForegroundColor Cyan
$usbDevices = usbipd list

if (-not $usbDevices) {
    Write-Host "No USB devices found. Ensure your USBIPD service is running and devices are connected." -ForegroundColor Red
    exit
}

# Parse the `usbipd list` output using regex
$deviceList = @()
$usbDevices -split "`n" | ForEach-Object {
    if ($_ -match "^(?<BUSID>\S+)\s+(?<VIDPID>\S+)\s+(?<Device>.+?)\s+(?<State>Shared|Not shared|Attached)$") {
        $deviceList += [PSCustomObject]@{
            BUSID   = $matches['BUSID']
            VIDPID  = $matches['VIDPID']
            Device  = $matches['Device']
            State   = $matches['State']
        }
    }
}

if (-not $deviceList) {
    Write-Host "No USB devices were found. Ensure devices are connected and try again." -ForegroundColor Red
    exit
}

# Filter for attached devices
$attachedDevices = $deviceList | Where-Object { $_.State -eq "Attached" }

if (-not $attachedDevices) {
    Write-Host "No devices are currently attached to WSL." -ForegroundColor Yellow
    exit
}

# Display the list of attached devices for selection
Write-Host "Select a device from the list in the graphical window to detach..."
$selectedDevice = $attachedDevices | Out-GridView -Title "Select a USB Device to Detach from WSL" -PassThru

if (-not $selectedDevice) {
    Write-Host "No device selected. Exiting." -ForegroundColor Yellow
    exit
}

# Detach the selected BUSID
$selectedBusID = $selectedDevice.BUSID
usbipd detach --busid $selectedBusID
if ($LASTEXITCODE -eq 0) {
    Write-Host "Device with BUSID $selectedBusID successfully detached from WSL." -ForegroundColor Green
} else {
    Write-Host "Failed to detach device with BUSID $selectedBusID. Check the device state and try again." -ForegroundColor Red
}


# # NOTICE - DO NOT EDIT this file in this folder. Copy this to a local .DEV folder and edit there.

# # Before running these commands, you must have the USBIPD-WIN project installed on Windows.
# # Follow the instructions at https://learn.microsoft.com/en-us/windows/wsl/connect-usb

# # This script allows you to detach usb devices from WSL back to Windows without physically unplugging the USB device


# # -- EDIT BELOW -- #

# # UNCOMMENT THE NEXT TWO LINES AND EDIT THE BUS ID WITH THE CORRECT ONE FOR YOUR USB DEVICE (use `usbipd list` to check your BUSID)
# usbipd detach --busid 1-3
# Write-Host "Don't forget to check to see that this device is available in WSL. Run `lsusb` in WSL to verify" -ForegroundColor Green 

# # COMMENT THE NEXT LINE
# # Write-Host "NO USB DEVICE SET FOR ATTACHING. EDIT THIS SCRIPT AND UPDATE THE LINE ABOVE THIS ONE." -ForegroundColor Red 
