# NOTICE - DO NOT EDIT this file in this folder. Copy this to a local .DEV folder and edit there.

# Before running these commands, you must have the USBIPD-WIN project installed on Windows.
# Follow the instructions at https://learn.microsoft.com/en-us/windows/wsl/connect-usb

# This script allows you to share usb devices on Windows to WSL. This does not attach the USB device in WSL.
# First the USB device must be shared, then it can be attached. See `attach-usb.ps1` and `detch-usb.ps1`.

# Script `share-usb.ps1` only needs to be run once to share the device. 

# List all of the USB devices connected to Windows by opening PowerShell in administrator mode and entering the following command. 
# Once the devices are listed, select and copy the bus ID of the device you’d like to attach to WSL.
Write-Host "______________________________________________" -ForegroundColor Green
Write-Host "Listing All USB Devices on your Windows system" -ForegroundColor Green
Write-Host "______________________________________________" -ForegroundColor Green

usbipd list
# This should output something like:
# BUSID  VID:PID    DEVICE                                                        STATE
# 1-3    0c45:674f  Integrated Webcam, Integrated IR Webcam, USB DFU              Not shared
# 1-14   8087:0033  Intel(R) Wireless Bluetooth(R)                                Not shared
# 3-5    413c:b06e  USB Input Device                                              Not shared
# 4-4    0bda:8153  Realtek USB GbE Family Controller                             Not Shared
# 6-4    0bda:1100  USB Input Device                                              Not shared
# 7-1    046d:0825  Logi C270 HD WebCam                                           Not shared
# 7-2    046d:c548  Logitech USB Input Device, USB Input Device                   Not shared
# 7-5    413c:b06f  USB Input Device                                              Not shared
# 8-4    413c:2110  USB Input Device                                              Not shared

# Before attaching the USB device, the command usbipd bind must be used to share the device, allowing it to be attached to WSL. 
# NOTE: This requires administrator privileges.


# -- EDIT BELOW -- #

# UNCOMMENT THE NEXT TWO LINES AND EDIT THE BUS ID (i.e. 7-1 from column "BUSID" above) WITH THE CORRECT ONE FOR YOUR USB DEVICE
# usbipd bind --busid <busid>
# usbipd list

# COMMENT THE NEXT LINE
Write-Host "NO USB DEVICE SET FOR BINDING. EDIT THIS SCRIPT AND UPDATE THE LINE ABOVE THIS ONE." -ForegroundColor Red 


# After running the command, verify that the device is shared using the command usbipd list again.